### ISSUE TITLE
Whistles (and probably coal) activate on both left and right click

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/minecraft__tamingplus#1]
Most likely need to detect if the player has clicked the right mouse button. Performing actions on left click will confuse some players and isn't aligned with Minecraft's base user experience.

**Comment by Zorro909** [comment]
Coal is most definitely not affected, since it's executed on EntityInteract, which is only happening on a Right Click
And the Whistle should be fixed by PR #2
